language: php

php:
- 5.3
- 5.4

env:
  global:
  - CI_HOME=$TRAVIS_BUILD_DIR

sudo: false

before_install:
- gem install sass
- gem install compass
- gem install jsduck
- npm install -g grunt-cli
- npm install
- curl -s https://getcomposer.org/installer | php --


before_script:
- php composer.phar install --dev
- mv $CI_HOME/server/php/Webservice/Database/DbConfig.example.php $CI_HOME/server/php/Webservice/Database/DbConfig.php
- phpenv rehash

script: ant -f build_kort.xml build

before_deploy: $CI_HOME/deploy_heroku.sh

deploy:
  provider: heroku
  strategy: api
  skip_cleanup: true
  app:
    master: kort
    develop: kort-dev
  on:
    repo: kort/kort
    php: '5.4'
  api_key:
    secure: NL10DAVFJJPk7mHdKeN3q5hpKgRq/gKpEnsXeBb7dDcnW0XuwmO88srMVbYHOA6w3kw50aPkKZ1AirElPjcpm2uxEz/tW7PpshY8fGDKdCyuczXKh24avTpD8nF8lskTIPXVpwWBYxCoFziRsd+eQBKHCsRyrQcv0mjg2j2MoNE=
